=== EvaCheer/caveCatalog/caves.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cavesInBulgaria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cavesList">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cave" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:string" />
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="alternativeNames">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0">
                                                    <xs:element name="alternativeName" minOccurs="0"
                                                        type="xs:string"
                                                        maxOccurs="unbounded" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="BFSpNumber" type="xs:string" />
                                        <xs:element name="regionAndCaveNumber" type="xs:string" />
                                        <xs:element name="location">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="administrative">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="province"
                                                                    type="xs:string" />
                                                                <xs:element name="municipality"
                                                                    type="xs:string" />
                                                                <xs:element name="settlement"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                            <xs:attribute name="EKATTENumber"
                                                                type="xs:integer" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="geographical">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="region"
                                                                    type="xs:string" />
                                                                <xs:element name="regionId"
                                                                    type="xs:string" />
                                                                <xs:element name="area"
                                                                    type="xs:string" />
                                                                <xs:element name="locality"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="characteristics">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="morphologicalType"
                                                        type="xs:string" />
                                                    <xs:element name="morphologicalTypeID"
                                                        type="xs:string" />
                                                    <xs:element name="levelOfHumidity"
                                                        type="xs:string" />
                                                    <xs:element name="measurements">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="length">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension
                                                                                base="xs:string">
                                                                                <xs:attribute
                                                                                    name="unitOfMeasurement"
                                                                                    use="required"
                                                                                    fixed="meters" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="denivelation">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension
                                                                                base="xs:string">
                                                                                <xs:attribute
                                                                                    name="unitOfMeasurement"
                                                                                    use="required"
                                                                                    fixed="meters" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="depth">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension
                                                                                base="xs:string">
                                                                                <xs:attribute
                                                                                    name="unitOfMeasurement"
                                                                                    use="required"
                                                                                    fixed="meters" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="altitude">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension
                                                                                base="xs:string">
                                                                                <xs:attribute
                                                                                    name="unitOfMeasurement"
                                                                                    use="required"
                                                                                    fixed="meters" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tours">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="tour" minOccurs="0"
                                                        maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="date"
                                                                    type="xs:date" />
                                                                <xs:element name="timeOfDay"
                                                                    type="xs:time" />
                                                                <xs:element name="guide"
                                                                    type="xs:string" />
                                                                <xs:element name="pricing">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element
                                                                                name="adultPrice"
                                                                                type="xs:decimal" />
                                                                            <xs:element
                                                                                name="childrenPrice"
                                                                                type="xs:decimal" />
                                                                            <xs:element
                                                                                name="studentPrice"
                                                                                type="xs:decimal" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>

                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="regionsList">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="regionInfo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="regionName" type="xs:string" />
                                        <xs:element name="reg">
                                            <xs:complexType>
                                                <xs:attribute name="regRef" use="required" />
                                                <xs:attribute name="regIdRef" type="xs:integer"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="morphologicalTypesList">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="morphologicalTypeInfo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="morphologicalType" type="xs:string" />
                                        <xs:element name="type">
                                            <xs:complexType>
                                                <xs:attribute name="typeRef" use="required" />
                                                <xs:attribute name="typeIDRef" type="xs:integer"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EvaCheer/caveCatalog/caves.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cavesCat.xsl"?>

<cavesInBulgaria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="caves.xsd">
    <cavesList>
        <cave>
            <id>1</id>
            <name>Леденика</name>
            <alternativeNames>
                <alternativeName>Леденица</alternativeName>
                <alternativeName>Леденик</alternativeName>
                <alternativeName>Леденикът</alternativeName>
            </alternativeNames>
            <BFSpNumber>1356</BFSpNumber>
            <regionAndCaveNumber>203141</regionAndCaveNumber>
            <location>
                <administrative EKATTENumber="12259">
                    <province>Врачанска област</province>
                    <municipality>Враца</municipality>
                    <settlement>гр.Враца</settlement>
                </administrative>
                <geographical>
                    <region>Старопланинска област</region>
                    <regionId>102</regionId>
                    <area>Врачански район</area>
                    <locality>Леденишки увал</locality>
                </geographical>
            </location>
            <characteristics>
                <morphologicalType>Пропастна пещера</morphologicalType>
                <morphologicalTypeID>200</morphologicalTypeID>
                <levelOfHumidity>Влажна, С лед</levelOfHumidity>
                <measurements>
                    <length unitOfMeasurement="meters">320</length>
                    <denivelation unitOfMeasurement="meters">37</denivelation>
                    <depth unitOfMeasurement="meters">14</depth>
                    <altitude unitOfMeasurement="meters">871</altitude>
                </measurements>
            </characteristics>
            <tours>
                <tour>
                    <date>2025-06-20</date>
                    <timeOfDay>10:00:00</timeOfDay>
                    <guide>Анна Георгиева</guide>
                    <pricing>
                        <adultPrice>28</adultPrice>
                        <childrenPrice>14</childrenPrice>
                        <studentPrice>19</studentPrice>
                    </pricing>
                </tour>
                <tour>
                    <date>2025-08-12</date>
                    <timeOfDay>15:30:00</timeOfDay>
                    <guide>Иван Петров</guide>
                    <pricing>
                        <adultPrice>30</adultPrice>
                        <childrenPrice>15</childrenPrice>
                        <studentPrice>20</studentPrice>
                    </pricing>
                </tour>
            </tours>
        </cave>
        <cave>
            <id>2</id>
            <name>Дяволското гърло</name>
            <alternativeNames>
                <alternativeName>Хърлога</alternativeName>
                <alternativeName>Харлога</alternativeName>
                <alternativeName>Клокотник</alternativeName>
            </alternativeNames>
            <BFSpNumber>0792</BFSpNumber>
            <regionAndCaveNumber>408003</regionAndCaveNumber>
            <location>
                <administrative EKATTENumber="73105">
                    <province>Смолянска област</province>
                    <municipality>Община Девин</municipality>
                    <settlement>с.Триград</settlement>
                </administrative>
                <geographical>
                    <region>Рило-Родопска област</region>
                    <regionId>104</regionId>
                    <area>Триградски район</area>
                    <locality>Триградско ждрело</locality>
                </geographical>
            </location>
            <characteristics>
                <morphologicalType>Пропастна пещера</morphologicalType>
                <morphologicalTypeID>200</morphologicalTypeID>
                <levelOfHumidity>Водна</levelOfHumidity>
                <measurements>
                    <length unitOfMeasurement="meters">548</length>
                    <denivelation unitOfMeasurement="meters">102</denivelation>
                    <depth unitOfMeasurement="meters">102</depth>
                    <altitude unitOfMeasurement="meters">1054</altitude>
                </measurements>
            </characteristics>
            <tours>
                <tour>
                    <date>2025-06-22</date>
                    <timeOfDay>09:00:00</timeOfDay>
                    <guide>Петя Иванова</guide>
                    <pricing>
                        <adultPrice>24</adultPrice>
                        <childrenPrice>12</childrenPrice>
                        <studentPrice>17</studentPrice>
                    </pricing>
                </tour>
                <tour>
                    <date>2025-06-23</date>
                    <timeOfDay>13:00:00</timeOfDay>
                    <guide>Борислав Колев</guide>
                    <pricing>
                        <adultPrice>26</adultPrice>
                        <childrenPrice>13</childrenPrice>
                        <studentPrice>18</studentPrice>
                    </pricing>
                </tour>
                <tour>
                    <date>2025-06-24</date>
                    <timeOfDay>16:00:00</timeOfDay>
                    <guide>Кристина Петрова</guide>
                    <pricing>
                        <adultPrice>22</adultPrice>
                        <childrenPrice>11</childrenPrice>
                        <studentPrice>16</studentPrice>
                    </pricing>
                </tour>
            </tours>
        </cave>
        <cave>
            <id>3</id>
            <name>Духлата</name>
            <alternativeNames>
                <alternativeName>Дулата</alternativeName>
            </alternativeNames>
            <BFSpNumber>0946</BFSpNumber>
            <regionAndCaveNumber>303002</regionAndCaveNumber>
            <location>
                <administrative EKATTENumber="5760">
                    <province>Пернишка област</province>
                    <municipality>Община Перник</municipality>
                    <settlement>с. Боснек</settlement>
                </administrative>
                <geographical>
                    <region>Крайщенско-Тракийска област</region>
                    <regionId>103</regionId>
                    <area>Голобърдско-Боснешки район</area>
                    <locality>Голяма могила</locality>
                </geographical>
            </location>
            <characteristics>
                <morphologicalType>Пропастна пещера</morphologicalType>
                <morphologicalTypeID>200</morphologicalTypeID>
                <levelOfHumidity>Суха, Влажна, Водна, Периодично водна</levelOfHumidity>
                <measurements>
                    <length unitOfMeasurement="meters">18200</length>
                    <denivelation unitOfMeasurement="meters">73</denivelation>
                    <depth unitOfMeasurement="meters">73</depth>
                    <altitude unitOfMeasurement="meters">992</altitude>
                </measurements>
            </characteristics>
            <tours>
                <tour>
                    <date>2025-12-06</date>
                    <timeOfDay>10:30:00</timeOfDay>
                    <guide>Михаил Димитров</guide>
                    <pricing>
                        <adultPrice>27</adultPrice>
                        <childrenPrice>14</childrenPrice>
                        <studentPrice>19</studentPrice>
                    </pricing>
                </tour>
                <tour>
                    <date>2025-06-28</date>
                    <timeOfDay>14:00:00</timeOfDay>
                    <guide>Силвия Николова</guide>
                    <pricing>
                        <adultPrice>25</adultPrice>
                        <childrenPrice>13</childrenPrice>
                        <studentPrice>18</studentPrice>
                    </pricing>
                </tour>
                <tour>
                    <date>2025-06-27</date>
                    <timeOfDay>09:30:00</timeOfDay>
                    <guide>Александър Стоянов</guide>
                    <pricing>
                        <adultPrice>30</adultPrice>
                        <childrenPrice>15</childrenPrice>
                        <studentPrice>20</studentPrice>
                    </pricing>
                </tour>
            </tours>
        </cave>
        <cave>
            <id>4</id>
            <name>Бачо Киро</name>
            <alternativeNames>
                <alternativeName>Мечата дупка</alternativeName>
                <alternativeName>Малката</alternativeName>
            </alternativeNames>
            <BFSpNumber>0512</BFSpNumber>
            <regionAndCaveNumber>214022</regionAndCaveNumber>
            <location>
                <administrative EKATTENumber="23947">
                    <province>Габровска област</province>
                    <municipality>Община Дряново</municipality>
                    <settlement>гр. Дряново</settlement>
                </administrative>
                <geographical>
                    <region>Старопланинска област</region>
                    <regionId>102</regionId>
                    <area>Стражанско-Дебелдялски район</area>
                    <locality>х.Бачо Киро</locality>
                </geographical>
            </location>
            <characteristics>
                <morphologicalType>Етажна пещера</morphologicalType>
                <morphologicalTypeID>202</morphologicalTypeID>
                <levelOfHumidity>Суха, влажна</levelOfHumidity>
                <measurements>
                    <length unitOfMeasurement="meters">3260</length>
                    <denivelation unitOfMeasurement="meters">65</denivelation>
                    <depth unitOfMeasurement="meters">65</depth>
